language: go
services:
- docker
go:
- '1.9'
branches:
  only:
  - master
env:
  global:
  - REPO=xtradio/api
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: hgJ18j3RJa4+nY+SH6CpOtv+M57zX0CHD+Q4KlSIKlPo7ZaYNuTEl0YIWfqVEQ+faob347Gs3cb/7flciIa47lcI1RDqQPKHvv2rIEafTqkrUIXHdBn5OfeDXDz9uKB146ruytEZ6Bnl3f4RECwBN2e6ncywZjQufAiM/eoID2d1lPz8Gu1kyRnFxiX4swyp4AKBpZvKN28nKjqJ/bJhv+zT+s+uLh9OyftDglSXuNZ4qmqBAQHbmrQPqbhx6LD2i3eZXUUsibNJTfckbMKadbxX6CYRENAVwgU+lGVZZiChUYOc+3T7uhIDQh9tIDQPPiewaTqDeBfkwsNF9jSrBACtWBiMG9A8RVhScDAE08RhtZN7j2XxRgWbkj4hTzgPPRhVS/yCb0K4GbFQgiMyxJEztaMPjTwcpU/b7FbOS91t8ikuhwqFMBjjdpiv+ARn6AoYKAgcR3XLKhH9qntoDqL2YteovuO3wsEa+fZCjfYbXoJE3T4+yG4IgXb7VA5RTLrE2OAOOtPkYzIYKFTrcBPPwquxj7mAiFCJxQSv842NBQsw+bSCy2oNfFqO4ffa/R9/eXijLZ6cN8EbpAAEkhFeOF0pjwS1P9YCvh6MXTabyKv4SUxOhX28P0GcrbxLOjH+oxqKMeHWGipQW+ElzGi0GMyc05GNbT8dKOhKnxI=
  - secure: ARZEQ9kDz15yANxaTvpwijTpjlAXa5yVq2VFt6eeoT8Gmm6d/eME+8+VDt+DiwYhhcfkWrgOFwiF3nv4YE0d+7yelcNCKQTTpETtdOv48MazSoHJVKcRaW3crpyF4mGC1Tnp6AA6s9VftANr3s5Q4SBhb/UApI6VGlRIhPY+Rc4Usrp5rcB0kc31PgVsSG1YvXPlofHvbbaBenS1oGzOb8b1ZZF8awoqUbmRNcHRtc7H02PdXfz+22hRpt/hKfjsa8cnwtM6pbUgyaeykDuRWLfNYxH+fnAlEfaYmHvW0aUQN+zKPU8u83opSXefZPHEO+HiguaexacbOl9RJUc2vmFunjSpcEjZku5SUFAKN7GNtNleVNdim5ghNjro9PqsibLfM++reY1ga9CbwOP7oT251+atv9xfAuuOZZKrnURLLXQFazj6hDub9cZ+coOs8rJ6C0AswETAK2zyNLpsIb5FLWC2MjSRL+IX+MOQ08NvFAmV2y3Xah9gQ6F4+hTOM5O60vDpgeir2YCyzwNIrwocuJiQtmvlayIwz9a2+KLo7ZNMlBWAcVq5ibwEafwG/nA91j3NkBfu4SyaEkCKkQgEA6wBAPijpPBQflUxpHPQ3rvYb4ZNAHBz1KRHBK3ULOZj1uJfx6tvG5C5Q+CEdM1z23KWnAfuMBza5AMK4CE=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: QGX/KihrhG2fi1PkvXimOjhXbUVF1PNCzqPqz/zTfbOga6O08G8MkW72VBWHkqhI7uWteJB3Pj0nMNGH9+/5pHBSlzwohz6zbetHypt0S7UFjH4Yc8aXQXAWO5Z7NKTCDaIW3E+uPuigODy84xOf21dzl08xNOOWx2xMHA53iXOG4ceX3faAM6kQCTCIPrxqFRiXKwn1HDWa7BjYGdYgQZzI6/6TWBsc0K+phvqVRQ0zGDQh84e0oOLhNxNUMvt6q0CCiLOQC6mTMEPmpESRkcBgNj/s9wEcKHnfTRcoLne6UFdoHCOOTbUSavZnTo2AkIvpbK6uwTZHz/J7A0EEkTNbwQgBgFpYcG4vRX5MWmHXnusIHh5GkNLzTmR9Xsdv24xsuA0D8XFXGDYvuqobVkbd4PivuCAqvn5ynHzqQWepr4sx6Atx+q2aArm1g0Rrk01XoTlL3sW1SgP7vbdUnPe/PNgMMOA27yWjAbOByXGrteKTy5ZeFEoIvIhWhWO9d2Tho3pQbpwDfG/PlLXwWj3PdeEc5njDCAWI2xhzpI53JQe+cwslMzO0xPFrCZP9nfyf0yukHmyJ+hmkSh8nLuUtpxKFBq+NkTZTtGH9cfFg8TwoT2m6PVT55BEPsTLNeB7lTS0eNr4Sh7AX+IKYCDKa2+4OyaAKWy+lN2HzZ9E=
after_success:
- docker build -f Dockerfile -t $REPO:latest .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
