language: go
services:
- docker
go:
- '1.13'
env:
  global:
  - REPO=xtradio/api
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DKpOxmZ/xuVlRRQBr6FLKmu3dUbvalkUjDZ1IG9UBu4QRLNbJkD3aAua2m8zAqkienkHm5QhGbvxuxe57X+HCvQvC7hbtx26vD0tcx4IUBY7WmvclSWy1Fn5Wsj36fqhKt1iY/ZXcd4+xuGGbAu+V2tB+NCcyUXcu+lHlElw206uEx+EuorKzxj1JlO0nD56JnOBXr9oq2++hYA9KkLKZ+saWU7sb7o5D50qb3xdpDoJnIn9GtdzDPjT5Dt08AEH+tnrMfNnWMJujoTGBU376MsYXhDshCmxWKgoG/8DGqq1G6vpg/rf71CUXiodqidYqHLo8hTJgHwGYdihDw2HRlyRKOE3ffLPSeJb26mxwNhsH7+GKH6lFJtmRRGWNGDU+dtJx43G5yNJTB/42Uri0lFUReCtFnNNr3IYS5NYvQz5Ayu1r3NvQaCOO8PfvYcZa04F5z8qdL2UQbF7ZkQOWtkEY6TC9Z28v6gmWPLHQeBB6lHs2JWhVLoJJBsWq2Zvgp4RlWft10FTmsIqPldd9RSv9y/We4pEK5U04LA1g4gRh0rknDPecAxvbnfNvLlaYPXMnbWYpN5wQEofUkFHfwL9VUZs2F4vvrgB7v6vxe0TfduJDrPQ8ISjb40+N1eLX6XKqKo/+FedfECxoqDvoGibOMnpwHmYAZKPlctWols=
  - secure: QrO6UBF173H7VhFTIA93O+Ah8KpY2dVorj1Bvkdg0obF4Ge+lr7WvA9Lx23yJIGof57s+aH5LDvHRkU95Tk9Qv8CCFB3fCucdiFg2riNyZ3xxp8BL42Wyut/bI8oj4epA1yc7nBwBJCoJKhq3VA0Ydyf+AhIy3lwK8VP1YycH1q6pEYfE4FK4MrzGfa+Ne93BSew4Dty6bbj4eJ+oOCMXa+chH1nPsXlioj3BTb0MUmtAUX0CMA9U0eEltpPywXAw1wgiDJxgIc2EKorj4pQozbGEohkAzkB8P0oRTWBjB4K6FFdKqEfvNfE2fcF6DXKk4RxosLdvDQu1gYfam5fEaDxRKTCx+Wslfg14Ix8q7WJhGp4tU0RyEV6oX5ULDzDIKsl+JLrq31ctO6p4NpJQeZ8FPEf6ED/57Ujp8GM0quvNk0xRauaNGBJlcAkIeVvuK/fC4HjfMNU5jLR5AL1S1R0+6EG0Ot/LmVm+pTUrlpAEry/Sw1QEmRW2fOXUeBt9ZsS+d2mRoHmDR2Ucy7NCMUHpcc+oBIeMIAk7Mb6JxVCgn6MwTzdFVw1/dOSWaaJgn4eqwX6y9S0fzH8qXIQMgg0HKxdCEf/QIaSF8HcPOjY0Qsoaha4NLjS2j2IuGV2JfZTJBxntvG4u3Rr/MoHoFtXpiP1AjGa3v+wOBYhk58=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: QGX/KihrhG2fi1PkvXimOjhXbUVF1PNCzqPqz/zTfbOga6O08G8MkW72VBWHkqhI7uWteJB3Pj0nMNGH9+/5pHBSlzwohz6zbetHypt0S7UFjH4Yc8aXQXAWO5Z7NKTCDaIW3E+uPuigODy84xOf21dzl08xNOOWx2xMHA53iXOG4ceX3faAM6kQCTCIPrxqFRiXKwn1HDWa7BjYGdYgQZzI6/6TWBsc0K+phvqVRQ0zGDQh84e0oOLhNxNUMvt6q0CCiLOQC6mTMEPmpESRkcBgNj/s9wEcKHnfTRcoLne6UFdoHCOOTbUSavZnTo2AkIvpbK6uwTZHz/J7A0EEkTNbwQgBgFpYcG4vRX5MWmHXnusIHh5GkNLzTmR9Xsdv24xsuA0D8XFXGDYvuqobVkbd4PivuCAqvn5ynHzqQWepr4sx6Atx+q2aArm1g0Rrk01XoTlL3sW1SgP7vbdUnPe/PNgMMOA27yWjAbOByXGrteKTy5ZeFEoIvIhWhWO9d2Tho3pQbpwDfG/PlLXwWj3PdeEc5njDCAWI2xhzpI53JQe+cwslMzO0xPFrCZP9nfyf0yukHmyJ+hmkSh8nLuUtpxKFBq+NkTZTtGH9cfFg8TwoT2m6PVT55BEPsTLNeB7lTS0eNr4Sh7AX+IKYCDKa2+4OyaAKWy+lN2HzZ9E=
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -f Dockerfile -t $REPO:$TRAVIS_BRANCH-$COMMIT .
- docker tag $REPO:$TRAVIS_BRANCH-$COMMIT $REPO:$TAG
after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push $REPO:$TAG
- docker push $REPO:$TRAVIS_BRANCH-$COMMIT
