language: go
services:
- docker
go:
- '1.13'
env:
  global:
  - REPO=xtradio/api
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: DzJxGjRNKnCo+HmRUhiVmQ3BUI25t3LtbOx/b1LVoDJ8RDtYmBreR+EQaLOH6jF7PLw8ou5u+3ovaOcvpapDGpZBRJ7rbIw6U5Qqc4Gay5Kg1X0B9rtwV7x2CJHRM0ZHArS3nMafRks0hYctehbxJxjo2jH4fL2Eh70Hy6hXqVQmcf5yCsAUwWBYk1+p6DjhQtEGs/qVsdtmlKCSS2F2rKf6O1OjPSyKg4lVR6v+n0ijLHJcyvhhmV/HFlZchBhZyO1nosYZC8oBdG+wDMiZEai5PcIp/7gF58vWWacxYJH2aMS7WY5A0ayg8xsTwXtfg/ZOPOCCuI8qnZCu8yB2Liu2gOTKfeCNTOv1zGqV74PE0pcbOgopqt8Ayem/eHwyDVMntWrxbyx7gKhkgZ6atoqxHwUTdHmq8909AdbW1jmAisW6v2M68KS6mYtV0isnbE2SLYrd6S6d9iLeJZ+5uQ8AJV+2uFo2tSS20WqCu2A0j7OAQXPuMO3FQkRpG1PKJyVJJ1YhYDlvMbszN9VaX0TnQ5Ti0YoKvlWFMF52W3cQY3GeHUTNZruaaQyIDmZEjxNeG4EyDdPJZJjpRiR9sEojfsJeYXENqdHlQTsDuiYNfiv2zAP3L6wJ9BsU0PKgCYVlM/yHRp0+J24F5jvSMSRbVDwSTCYkk0v+EbZZ0BE=
  - secure: idgJEmsLz1BrkNV+mKZjP05KPk3ju61OrbSLznaOftv98LGNmCgo6MsX9oVREsjjQsB5xPd0C3Od0DrcXwYUxppvS/WYRcFzz0aoO3btxNCNzK5Th/gYE48LK2cE+mvubN3WZQXt3uk/gCccFSNudFeR0L8mQIfv6r84IuOoJHyIjLBg0K9YUOYevyoFuc0X2jOqfMGRu5LOVT36flctVqslnwx8xHcLLFCvL026hdWHTF55EgTVmPJLElJY0jk2zrwFTjlmRMUSVaTLC2xkrAb1v3DVTEyj6ps5RK78DiagBrlNdjKKV74u3tO7OwiMTr6DoX5VZ4OEb+BeM6J0OykBnwxV07l7uSS/b+tWMMzCMnEb+jD97q+T2FeTtg1/TmADLKh8jsKjm/X35ScHIy6QlcH/GxMwNdkkNTEtXjI8V7H11xGt1TXsXcpi133KIUgMJwI281WD5t7DePMieIt59rjB2PaQ4MsiuTwWptaubGhekVQ/zgcxDOj5SKIBF5BCggDdVGSi6QWaCdxGIQfpzyNSmgCvpr3msWoT+Lbo4CrD8ETNJbcNA5AxgA9HQW59WrhmaVaTkqJ3QpK7XpKOkgag7fQPiC2Vxcjx+k7moIQ8GKCx1NnMc5BA7KANA3XlSlAD2iw/uYyiFuPEnCnpapGPBzL4Bfvgxm2m1r8=
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: QGX/KihrhG2fi1PkvXimOjhXbUVF1PNCzqPqz/zTfbOga6O08G8MkW72VBWHkqhI7uWteJB3Pj0nMNGH9+/5pHBSlzwohz6zbetHypt0S7UFjH4Yc8aXQXAWO5Z7NKTCDaIW3E+uPuigODy84xOf21dzl08xNOOWx2xMHA53iXOG4ceX3faAM6kQCTCIPrxqFRiXKwn1HDWa7BjYGdYgQZzI6/6TWBsc0K+phvqVRQ0zGDQh84e0oOLhNxNUMvt6q0CCiLOQC6mTMEPmpESRkcBgNj/s9wEcKHnfTRcoLne6UFdoHCOOTbUSavZnTo2AkIvpbK6uwTZHz/J7A0EEkTNbwQgBgFpYcG4vRX5MWmHXnusIHh5GkNLzTmR9Xsdv24xsuA0D8XFXGDYvuqobVkbd4PivuCAqvn5ynHzqQWepr4sx6Atx+q2aArm1g0Rrk01XoTlL3sW1SgP7vbdUnPe/PNgMMOA27yWjAbOByXGrteKTy5ZeFEoIvIhWhWO9d2Tho3pQbpwDfG/PlLXwWj3PdeEc5njDCAWI2xhzpI53JQe+cwslMzO0xPFrCZP9nfyf0yukHmyJ+hmkSh8nLuUtpxKFBq+NkTZTtGH9cfFg8TwoT2m6PVT55BEPsTLNeB7lTS0eNr4Sh7AX+IKYCDKa2+4OyaAKWy+lN2HzZ9E=
script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER

after_success:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  - docker push $REPO:$TAG
  - docker push $REPO:$COMMIT
